//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.04 at 05:33:53 PM CST 
//


package org.leopardocs.autotips.core.config;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="errorNotify" type="{http://config.core.autotips.leopard.org}ErrorNotify" minOccurs="0"/>
 *         &lt;element name="autotip" type="{http://config.core.autotips.leopard.org}Autotip" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "errorNotify",
    "autotip"
})
@XmlRootElement(name = "autotips")
public class Autotips {

    protected ErrorNotify errorNotify;
    protected List<Autotip> autotip;

    /**
     * Gets the value of the errorNotify property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorNotify }
     *     
     */
    public ErrorNotify getErrorNotify() {
        return errorNotify;
    }

    /**
     * Sets the value of the errorNotify property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorNotify }
     *     
     */
    public void setErrorNotify(ErrorNotify value) {
        this.errorNotify = value;
    }

    /**
     * Gets the value of the autotip property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the autotip property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAutotip().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Autotip }
     * 
     * 
     */
    public List<Autotip> getAutotip() {
        if (autotip == null) {
            autotip = new ArrayList<Autotip>();
        }
        return this.autotip;
    }

}
