//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.04 at 05:33:53 PM CST 
//


package org.leopardocs.autotips.core.config;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.leopard.autotips.core.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.leopard.autotips.core.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Source }
     * 
     */
    public Source createSource() {
        return new Source();
    }

    /**
     * Create an instance of {@link ErrorNotify }
     * 
     */
    public ErrorNotify createErrorNotify() {
        return new ErrorNotify();
    }

    /**
     * Create an instance of {@link Autotips }
     * 
     */
    public Autotips createAutotips() {
        return new Autotips();
    }

    /**
     * Create an instance of {@link FieldItem }
     * 
     */
    public FieldItem createFieldItem() {
        return new FieldItem();
    }

    /**
     * Create an instance of {@link Autotip }
     * 
     */
    public Autotip createAutotip() {
        return new Autotip();
    }

    /**
     * Create an instance of {@link SmtpConfig }
     * 
     */
    public SmtpConfig createSmtpConfig() {
        return new SmtpConfig();
    }

    /**
     * Create an instance of {@link Autotip.Fields }
     * 
     */
    public Autotip.Fields createAutotipFields() {
        return new Autotip.Fields();
    }

    /**
     * Create an instance of {@link Connection }
     * 
     */
    public Connection createConnection() {
        return new Connection();
    }

    /**
     * Create an instance of {@link Sources }
     * 
     */
    public Sources createSources() {
        return new Sources();
    }

}
