//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.04 at 05:33:53 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://config.core.autotips.leopard.org", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.leopardocs.autotips.core.config;
