package org.leopardocs.autotips.web;

import java.util.Date;

import javax.servlet.ServletContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.leopardocs.autotips.core.Configurator;
import org.leopardocs.autotips.core.config.Autotip;
import org.leopardocs.autotips.core.config.Autotips;
import org.leopardocs.autotips.core.config.ErrorNotify;
import org.leopardocs.autotips.core.indexer.CommonIndexer;
import org.leopardocs.autotips.core.tools.AutoTipsTools;

public class ControlPanelService {
	private static final Log logger = LogFactory
			.getLog(ControlPanelService.class);

	private static long refreshIndex(String id, ServletContext sc)
			throws Exception {
		long cost = 0L;
		if (id != null) {
			Date start = new Date();
			Date end = null;
			try {
				Autotips autoTips = AutoTipsServlet.getAutoTipsConfig();
				Configurator.getAutotip(autoTips, id);
				logger.info("Refresh AutoTip " + id + " index start...");
				if (id.equalsIgnoreCase("all")) {
					CommonIndexer.processAll(autoTips);
				} else {
					Autotip autoTip = Configurator.getAutotip(autoTips, id);
					if (autoTip != null) {
						CommonIndexer.process(autoTip);
					}
				}
				logger.info("Refresh AutoTip " + id + " index end.");
			} catch (Exception e) {
				throw e;
			} finally {
				end = new Date();
				cost = end.getTime() - start.getTime();
			}
		}
		return cost;
	}

	public static long refreshIndex(HttpServletRequest request,
			HttpServletResponse response) throws Exception {
		String id = request.getParameter("id");
		long cost = 0L;
		if (id != null) {
			try {
				cost = refreshIndex(id, request.getSession()
						.getServletContext());
			} catch (Exception e) {
				errorHappened(request.getSession().getServletContext(), e);
				e.printStackTrace();
				logger.error(e);
				throw e;
			}
		}
		return cost;
	}

	private static void errorHappened(ServletContext sc, Throwable throwable)
			throws Exception {
		ErrorNotify errorNotify = AutoTipsServlet.getAutoTipsConfig()
				.getErrorNotify();
		if ((errorNotify != null) && (errorNotify.getSmtpConfig() != null)) {
			StringBuilder builder = new StringBuilder();
			builder.append("This error message generated by LeopardOCS Autotips.\n");
			builder.append("When you receive this mail means Autotips have error occured, the error stack trace is: \n");
			builder.append(AutoTipsTools.getFullStackTrace(throwable));
			builder.append("\n\n");
			builder.append("or LeopardOCS Autotips support website: https://github.com/leopardos/autotips, thanks!");
			logger.error(builder.toString());
		}
	}
}